export const FETCH_LIST_CATEGORY = "FETCH_LIST_CATEGORY";
export const FETCH_LIST_CATEGORY_SUCCESS = "FETCH_LIST_CATEGORY_SUCCESS";
export const FETCH_LIST_CATEGORY_FALSE = "FETCH_LIST_CATEGORY_FALSE";
export const CATEGORY_LIST = "CATEGORY_LIST";
