export const FETCH_LIST_PRODUCT = "FETCH_LIST_PRODUCT";
export const FETCH_LIST_PRODUCT_SUCCESS = "FETCH_LIST_PRODUCT_SUCCESS";
export const FETCH_LIST_PRODUCT_FALSE = "FETCH_LIST_PRODUCT_FALSE";
export const PRODUCT_LIST = "PRODUCT_LIST";
export const PRODUCT_DETAIL = "PRODUCT_DETAIL";
